#! /bin/sh
# /etc/init.d/choose_repo
#
### BEGIN INIT INFO
# Provides: choose_repo
# Required-Start: $network
# Defalt-Start: 3 4 5
# Default-Stop: 0 1 2 6
# Description: Initializes the correct repo depending on the region.
### END INIT INFO

case "$1" in
    start)
        /usr/sbin/choose_repo.py
	;;
esac

exit 0
